// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6vAeM_PLhocKYBHfM5FLllz-jn9sngHg',
    appId: '1:784741802916:web:2e072dbce352673d3f9731',
    messagingSenderId: '784741802916',
    projectId: 'social-media-app-auth-e2ffb',
    authDomain: 'social-media-app-auth-e2ffb.firebaseapp.com',
    storageBucket: 'social-media-app-auth-e2ffb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOKo7AaC92LIY61xrXIkCBgrVAlL8asio',
    appId: '1:784741802916:android:cb34162a92f93be13f9731',
    messagingSenderId: '784741802916',
    projectId: 'social-media-app-auth-e2ffb',
    storageBucket: 'social-media-app-auth-e2ffb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBogveUM2Ec2Sj1K1_ElYhtfCU-S0xIszE',
    appId: '1:784741802916:ios:3a6785983eb956733f9731',
    messagingSenderId: '784741802916',
    projectId: 'social-media-app-auth-e2ffb',
    storageBucket: 'social-media-app-auth-e2ffb.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBogveUM2Ec2Sj1K1_ElYhtfCU-S0xIszE',
    appId: '1:784741802916:ios:3a6785983eb956733f9731',
    messagingSenderId: '784741802916',
    projectId: 'social-media-app-auth-e2ffb',
    storageBucket: 'social-media-app-auth-e2ffb.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6vAeM_PLhocKYBHfM5FLllz-jn9sngHg',
    appId: '1:784741802916:web:dc620dce38b0eae83f9731',
    messagingSenderId: '784741802916',
    projectId: 'social-media-app-auth-e2ffb',
    authDomain: 'social-media-app-auth-e2ffb.firebaseapp.com',
    storageBucket: 'social-media-app-auth-e2ffb.firebasestorage.app',
  );
}
